### ISSUE TITLE
Example of usage

### ISSUE THREAD

**Issue by AceTheWiz** [endpointsystems/ArangoDB.Net.Identity#1]
Can you possibly provide an example of how to use this library.

I tried starting with a standard Blazor Server project with **Authentication Type** set to **Individual Accounts**.

I removed the using references
```
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
```

I removed ```Migrations``` folder and the ```ApplicationDbContext.cs``` file

In ```public void ConfigureServices(IServiceCollection services)``` I replaced
```C#
services.AddDbContext<ApplicationDbContext>(options =>
options.UseSqlServer(
Configuration.GetConnectionString("DefaultConnection")));
services.AddDefaultIdentity<IdentityUser>(options => options.SignIn.RequireConfirmedAccount = true)
   .AddEntityFrameworkStores<ApplicationDbContext>();
```
with this code
```C#
ArangoDbIdentityConfiguration arangoDbConfig = new()
{
  ArangoDbSettings = new()
  {
    Uri = "http://127.0.0.1:8529",
    Database = "OrgData",
    UserId = "root",
    Password = "dbadmin"
  }
};

services.ConfigureArangoDbIdentity<ArangoIdentityUser> (arangoDbConfig);
```
The code builds and runs but when navigating to the ```Register``` or ```Login``` page, I get the ```Sorry, there's nothing at this address.``` page.

Could you help please.

**Comment by elvogel** [comment]
Hi,
When I initially put this together I ran into a ton of issues getting it working because the driver dependency was basically lacking all over the place. So this code is not production-ready at all. They've since done a lot to make the driver more feature-complete, but I haven't had a chance to get around to making any updates to reflect their changes.

**Comment by AceTheWiz** [comment]
Thanks for the reply. I would contribute but at this stage I know too little about how Authentication works.

**Comment by elvogel** [comment]
Yeah, I started with the MongoDB driver as the code base, but I ran into a ton of issues with the ArangoDb library because it wasn't where I needed it to be. To their credit, it probably is now, but I don't have the bandwidth at the moment to get this up to speed.
